Repository MT-CTF/capturetheflag, pull requests merged in 2018-12, with the labels that each got.

#295 Hide builtin nametags on join until replaced by entity nametags
  mods/playertag/api.lua
Labels: @ Audiovisuals, Bugfix, High Priority, Trivial

#263 Eliminate shooter's dependency on tnt_explode.ogg
  mods/shooter/shooter.lua
  mods/shooter/sounds/shooter_explode.ogg
Labels: @ Audiovisuals, Bugfix

#296 Improve vote_kick feature
  mods/vote/init.lua
  mods/vote/vote_kick.lua
Labels: @ AntiAbuse, Feature, Maintenance

#286 Clear kill list on new match
  mods/ctf_events/depends.txt
  mods/ctf_events/init.lua
Labels: @ Audiovisuals, Bugfix, Maintenance

#294 Fix team-chest shift-click
  mods/ctf_team_base/chest.lua
Labels: Bugfix, Medium Priority

#305 Replenish stamina on respawn
  mods/sprint/init.lua
Labels: Bugfix, High Priority, Trivial

#304 Add a random message for /r
  mods/random_messages/init.lua
Labels: Trivial

#307 Allow specifying optional param for /r
  mods/ctf_stats/gui.lua
Labels: Feature, Medium Priority, Trivial

#308 map_maker.lua: Fix missing assignment of return value
  mods/ctf_map/map_maker.lua
Labels: @ MapEditor, Bugfix, High Priority, Trivial

#317 Handle kill weapon type in ctf_events instead of ctf_pvp_engine
  mods/ctf_events/init.lua
Labels: Maintenance
