Repository MT-CTF/capturetheflag, pull requests merged in 2018-11, with the labels that each got.

#215 Add ceiling and bedrock during barrier placement
  mods/ctf_map/barrier.lua
Labels: @ MapEditor, @ Maps, @ Nodes

#213 Replace middle barrier with water if surrounded by water
  mods/ctf_map/barrier.lua
Labels: @ Maps

#227 Improve layout of ctf_map GUI
  mods/ctf_map/map_maker.lua
Labels: @ Audiovisuals, @ MapEditor

#235 Improved colored team door texture
  mods/doors/textures/doors_door_steel_blue.png
  mods/doors/textures/doors_door_steel_red.png
Labels: @ Audiovisuals

#236 Save map editor context to mod_storage until map has been exported
  mods/ctf_map/map_maker.lua
Labels: @ MapEditor, Feature

#234 Improve rankings formspec
  mods/ctf_stats/gui.lua
Labels: @ Audiovisuals

#204 Fix summary not stored before restart
  mods/ctf_stats/gui.lua
  mods/ctf_stats/init.lua
Labels: Bugfix

#246 Transfer all maps to maps repo
  mods/ctf_map/maps/01_two_hills.conf
  mods/ctf_map/maps/01_two_hills.mts
  mods/ctf_map/maps/02_bridge.conf
  mods/ctf_map/maps/02_bridge.mts
Labels: @ Maps

#252 Fix furnace and axe recipes
  mods/ctf_crafting/init.lua
Labels: Trivial

#250 Improve crafting recipe of ladder_wood
  mods/ctf_crafting/init.lua
Labels: @ AntiAbuse, @ Nodes, Bugfix, High Priority

#251 Delete default/crafting.lua
  mods/default/crafting.lua
  mods/default/init.lua
Labels: Maintenance, Trivial

#256 Update `stairs` to latest MTG version
  mods/stairs/README.txt
  mods/stairs/init.lua
  mods/stairs/textures/stairs_glass_outer_stairside.png
  mods/stairs/textures/stairs_glass_split.png
  mods/stairs/textures/stairs_glass_stairside.png
  mods/stairs/textures/stairs_obsidian_glass_outer_stairside.png
  mods/stairs/textures/stairs_obsidian_glass_split.png
  mods/stairs/textures/stairs_obsidian_glass_stairside.png
Labels: @ Nodes, Maintenance, Proposal/Suggestion

#245 Fix EOM shown before winner_player is initialized
  mods/ctf_stats/init.lua
Labels: Bugfix, High Priority

#254 Fix accidental inclusion of 5.0-only methods
  mods/ctf_map/map_maker.lua
Labels: @ MapEditor, Bugfix, High Priority

#262 Fix missing field: default.node_sound_snow_defaults
  mods/stairs/init.lua
Labels: Bugfix, High Priority, Trivial

#266 Add a 'x' minute temporary lockout feature when vote kicked
  mods/vote/init.lua
Labels: @ AntiAbuse, Feature, Testing needed

#283 Don't award points for suicide and disable player damage in shooter during buildtime
  mods/ctf_stats/init.lua
  mods/shooter/shooter.lua
Labels: @ AntiAbuse, @ Scoring, Bugfix, High Priority

#273 Remove unused arg from ctf_colors.get_color and ctf_colors.get_irc_color
  mods/ctf_bounties/init.lua
  mods/ctf_events/init.lua
Labels: Maintenance, Trivial

#277 Re-add mods/default/crafting.lua with only the fuel recipes
  mods/default/crafting.lua
  mods/default/init.lua
Labels: Bugfix, High Priority

#255 Create/Increase delay before attaching entities to players
  mods/gauges/init.lua
  mods/playertag/api.lua
  mods/wield3d/init.lua
Labels: Bugfix, High Priority

#272 Allow players to cross barrier if fly=true, interact=false
  mods/ctf_map/barrier.lua
Labels: Feature
