Repository MT-CTF/capturetheflag, pull requests merged in 2019-03, with the labels that each got.

#206 Add reinforced cobble
  mods/ctf/ctf_crafting/init.lua
  mods/ctf/ctf_team_base/nodes.lua
  mods/ctf_team_base/textures/ctf_team_base_reinforced_cobble.png
  mods/other/random_messages/init.lua
Labels: @ Nodes

#280 Make tsm_chests:chest indestructible
  mods/other/tsm_chests/init.lua
Labels: @ AntiAbuse, @ Nodes, Bug / Bugfix, Trivial

#363 Fix medkits HP leak due to missing check
  mods/pvp/medkits/init.lua
Labels: @ AntiAbuse, @ Player, Bug / Bugfix, High Priority, Trivial

#360 Add ctf_markers mod
  mods/ctf/ctf_marker/init.lua
  mods/ctf/ctf_marker/mod.conf
  mods/other/random_messages/init.lua
Labels: @ Audiovisuals, @ HUD, Feature, WIP

#370 Increase marker visibility time to 30 seconds
  mods/ctf/ctf_marker/init.lua
Labels: Trivial

#301 Add `hud_score` mod API
  mods/ctf/ctf_bounties/depends.txt
  mods/ctf/ctf_bounties/init.lua
  mods/ctf/ctf_stats/init.lua
  mods/pvp/hud_score/README.md
  mods/pvp/hud_score/init.lua
  mods/pvp/hud_score/mod.conf
Labels: @ Audiovisuals, @ HUD, @ Scoring, Feature, Testing needed

#327 Extend /summary to show scores of current match as well
  mods/ctf/ctf_stats/init.lua
  mods/other/random_messages/init.lua
Labels: @ Audiovisuals, Feature

#369 Update README
  README.md
Labels: Maintenance, Trivial

#364 Remove unused MTG features (Part 1)
  mods/mtg/default/init.lua
  mods/mtg/default/trees.lua
  mods/mtg/killme/init.lua
Labels: Maintenance

#289 Add physics modifiers wrapper mod for player physics overrides
  mods/other/sprint/depends.txt
  mods/other/sprint/init.lua
  mods/physics/init.lua
Labels: @ Player, Feature

#306 Refactor and clean-up map_maker.lua
  mods/ctf/ctf_map/map_maker.lua
Labels: Bug / Bugfix, High Priority, Maintenance

#372 Optimise hud_score register_globalstep
  mods/pvp/hud_score/init.lua
Labels: Testing needed

#374 Fix error thrown when param passed to get_player_by_name is nil
  mods/ctf/ctf_map/schem_map.lua
Labels: Bug / Bugfix, Trivial

#367 Rename indestructible wool nodes (+ documentation and cleanups)
  mods/ctf/ctf_map/README.md
  mods/ctf/ctf_map/nodes.lua
  mods/ctf/ctf_map/schem_map.lua
Labels: @ AntiAbuse, @ Documentation, @ Nodes, Maintenance

#210 Increase player movement speed
  minetest.conf
Labels: @ Player, Feature, Testing needed

#375 Update random message for reinforced cobble
  mods/other/random_messages/init.lua
Labels: Bug / Bugfix, Trivial

#331 Remove wooden tools
  mods/ctf/ctf_crafting/init.lua
  mods/ctf/ctf_map/chest.lua
  mods/ctf/ctf_map/give_initial_stuff.lua
  mods/mtg/default/aliases.lua
  mods/mtg/default/crafting.lua
  mods/mtg/default/textures/default_tool_woodaxe.png
  mods/mtg/default/textures/default_tool_woodpick.png
  mods/mtg/default/textures/default_tool_woodshovel.png
  mods/mtg/default/textures/default_tool_woodsword.png
  mods/mtg/default/tools.lua
  mods/other/wield3d/location.lua
  mods/pvp/dropondie/init.lua
Labels: @ Weapons, Balance, Medium Priority, Testing needed

#382 Move physics mod into "other" modpack
  mods/other/physics/init.lua
Labels: Maintenance, Trivial

#377 Fix indestructible snow and ice not being slippery
  mods/ctf/ctf_map/nodes.lua
Labels: @ Nodes, Bug / Bugfix, Trivial

#378 Add HUD score elements for flag pickup and capture
  mods/ctf/ctf_stats/init.lua
Labels: @ HUD, Feature, Trivial

#387 Add mod.conf for physics mod
  mods/other/physics/mod.conf
Labels: @ Documentation, Maintenance, Trivial

#386 shooter: Fix incorrect eye_height used for raytracing
  mods/pvp/shooter/shooter.lua
Labels: @ Weapons, Bug / Bugfix, High Priority, Trivial

#349 Improve grenades
  mods/pvp/shooter/grenade.lua
  mods/pvp/shooter/shooter.lua
Labels: @ Weapons, Balance, Bug / Bugfix, Testing needed, Trivial

#392 Revert "Increase player movement speed (#210)"
  minetest.conf
Labels: Balance, Bug / Bugfix, High Priority, Trivial

#394 physics: Remove asserts and physics.change
  mods/other/physics/init.lua
Labels: Bug / Bugfix, High Priority

#391 Remove game_api.txt and minetest.conf.example
  game_api.txt
  minetest.conf.example
Labels: @ Documentation, Maintenance, Trivial
