Repository MT-CTF/capturetheflag, pull requests merged in 2019-11, with the labels that each got.

#484 Make snow non-slippery again
  mods/ctf/ctf_map/nodes.lua
  mods/mtg/default/nodes.lua
Labels: :gear: Nodes, Balance, Ready for review :tada:, Trivial

#490 Improve display format of ctf.log
  mods/ctf/ctf/core.lua
Labels: Maintenance / Code quality, NO SQUASH :x:, Ready for review :tada:, Trivial

#493 ctf_map: Auto-replace stone with ind_stone_red when placing barriers
  mods/ctf/ctf_map/barrier.lua
Labels: :gear: Maps, Feature, Maintenance / Code quality, NO SQUASH :x:, Ready for review :tada:

#501 Disable knockback completely
  mods/ctf/ctf/core.lua
Labels: Approved :heavy_check_mark:, Balance, High Priority :grey_exclamation:

#500 ctf_match: Increase skip vote's required majority ratio to 0.6
  mods/ctf/ctf_match/vote.lua
Labels: :gear: AntiAbuse, Ready for review :tada:, Trivial

#503 [Trivial] Increase damage of spikes to justify its cost.
  mods/ctf/ctf_traps/init.lua
Labels: :gear: Weapons, Approved :heavy_check_mark:, Trivial

#508 Fix collision boxes of dead players not being restored on new match
  mods/pvp/collisionbox/init.lua
  mods/pvp/collisionbox/mod.conf
Labels: :gear: Player, Bug / Bugfix, High Priority :grey_exclamation:, Ready for review :tada:

#509 [Trivial] Change the map makers needed random message.
  mods/other/random_messages/init.lua
Labels: :gear: Documentation, Ready for review :tada:, Trivial

#513 Remove ctf.post() function and its instances in the code
  mods/ctf/ctf/teams.lua
  mods/ctf/ctf_flag/flag_func.lua
Labels: Approved :heavy_check_mark:, Maintenance / Code quality

#511 Remove redundant diplomacy textures
  mods/ctf/ctf/textures/diplo_alliance.png
  mods/ctf/ctf/textures/diplo_peace.png
  mods/ctf/ctf/textures/diplo_war.png
Labels: Approved :heavy_check_mark:, Maintenance / Code quality

#456 Parameterized /ctf_next; "Skip to map" and "Set as next map" buttons in maps catalog
  mods/ctf/ctf_map/maps_catalog.lua
  mods/ctf/ctf_map/schem_map.lua
Labels: :gear: Maps, Approved :heavy_check_mark:, Feature, NO SQUASH :x:, Ready for review :tada:

#514 update.sh: Use git submodule update instead of manually git pull-ing
  update.sh
Labels: Maintenance / Code quality, Ready for review :tada:, Trivial

#163 Improve /report; add report API
  mods/ctf/ctf_reports/README.md
  mods/ctf/ctf_reports/init.lua
  mods/ctf/ctf_reports/mod.conf
  mods/other/report/README.md
  mods/other/report/init.lua
Labels: :gear: AntiAbuse, Approved :heavy_check_mark:, Feature, Ready for review :tada:

#495 ctf_stats: Add map name to match summary
  mods/ctf/ctf_map/schem_map.lua
  mods/ctf/ctf_stats/gui.lua
  mods/ctf/ctf_stats/init.lua
Labels: Approved :heavy_check_mark:, Feature, Ready for review :tada:

#499 Remove redundant server join message; improve team join message
  mods/ctf/ctf/teams.lua
Labels: Approved :heavy_check_mark:, Feature, Ready for review :tada:

#516 Remove stone sword from default treasure registration
  mods/ctf/ctf_treasure/init.lua
Labels: :gear: Weapons, Approved :heavy_check_mark:, Ready for review :tada:

#491 Refactor ctf_stats [Part 1]
  mods/ctf/ctf_stats/chat.lua
  mods/ctf/ctf_stats/gui.lua
  mods/ctf/ctf_stats/init.lua
Labels: Approved :heavy_check_mark:, High Priority :grey_exclamation:, Maintenance / Code quality, Ready for review :tada:

#515 Maps Catalog: Fix crash when index is invalid
  mods/ctf/ctf_map/maps_catalog.lua
Labels: Bug / Bugfix, Ready for review :tada:, Trivial

#512 Remove redundant team ownership related code
  mods/ctf/ctf/teams.lua
  mods/ctf/ctf_chat/init.lua
Labels: Approved :heavy_check_mark:, Maintenance / Code quality, Ready for review :tada:

#454 ctf_stats: Add support for retrieving stats by rank
  mods/ctf/ctf_stats/chat.lua
  mods/ctf/ctf_stats/gui.lua
  mods/ctf/ctf_stats/init.lua
  mods/other/random_messages/init.lua
Labels: Approved :heavy_check_mark:, Feature, High Priority :grey_exclamation:, Maintenance / Code quality, Ready for review :tada:
