Repository MT-CTF/capturetheflag, pull requests merged in 2019-10, with the labels that each got.

#463 Add a 1000 score threshold to vote in vote kicks
  mods/other/vote/init.lua
  mods/other/vote/vote_kick.lua
Labels: @ AntiAbuse, Approved :heavy_check_mark:, Feature

#468 Better collision boxes
  mods/pvp/collisionbox/init.lua
  mods/pvp/collisionbox/mod.conf
Labels: @ AntiAbuse, @ Player, Approved :heavy_check_mark:, Feature

#467 Add colored random messages
  mods/other/random_messages/init.lua
Labels: @ Audiovisuals, Approved :heavy_check_mark:, Feature, Trivial

#451 Improve README.md
  README.md
Labels: @ Documentation

#478 Add support for optionally setting time per-map
  mods/ctf/ctf_map/README.md
  mods/ctf/ctf_map/init.lua
  mods/ctf/ctf_map/schem_map.lua
  mods/ctf/ctf_map/time.lua
  mods/ctf/ctf_match/matches.lua
Labels: @ Maps, Feature, Review required

#422 Improve log messages
  .luacheckrc
  mods/ctf/ctf_alloc/init.lua
  mods/ctf/ctf_bounties/init.lua
  mods/ctf/ctf_map/barrier.lua
  mods/ctf/ctf_map/maps_catalog.lua
  mods/ctf/ctf_map/schem_map.lua
  mods/ctf/ctf_marker/init.lua
  mods/ctf/ctf_match/chat.lua
  mods/ctf/ctf_playertag/api.lua
  mods/ctf/ctf_stats/gui.lua
  mods/ctf/ctf_stats/init.lua
  mods/mtg/game_commands/init.lua
  mods/other/report/init.lua
  mods/other/tsm_chests/init.lua
  mods/other/vote/init.lua
  mods/other/vote/vote_kick.lua
  mods/pvp/dropondie/init.lua
  mods/pvp/gauges/init.lua
Labels: Approved :heavy_check_mark:, High Priority, Maintenance / Code quality, Review required

#481 Add damage cobble to treasure chests
  mods/ctf/ctf_treasure/init.lua
Labels: Approved :heavy_check_mark:, Feature

#482 [Trivial] Fixing documentation for reinforced cobble
  mods/ctf/ctf_crafting/init.lua
Labels: Approved :heavy_check_mark:, Trivial

#471 Add support for per-map skyboxes
  mods/ctf/ctf_map/init.lua
  mods/ctf/ctf_map/schem_map.lua
  mods/ctf/ctf_map/time.lua
  mods/ctf/ctf_map/time_sky.lua
Labels: @ Maps, Approved :heavy_check_mark:, Feature, High Priority, NO SQUASH, Ready for review :tada:

#473 Add indestructible torch [ctf_map:torch]
  mods/ctf/ctf_map/nodes.lua
Labels: :gear: Nodes, Approved :heavy_check_mark:, Feature, Ready for review :tada:

#485 Map maker: Fix barrier rotation and outer barrier placement issues
  mods/ctf/ctf_map/barrier.lua
  mods/ctf/ctf_map/map_maker.lua
Labels: :gear: MapEditor, Bug / Bugfix, High Priority :grey_exclamation:, Trivial

#486 Fix crash upon invoking /maps_reload
  mods/ctf/ctf_map/schem_map.lua
Labels: Approved :heavy_check_mark:, Bug / Bugfix, High Priority :grey_exclamation:

#319 Allocate players into teams on the basis of cumulative team scores
  minetest.conf
  mods/ctf/ctf_alloc/init.lua
Labels: :gear: Teams, Action / change needed, Approved :heavy_check_mark:, Balance, High Priority :grey_exclamation:, Ready for review :tada:
