Repository MT-CTF/capturetheflag, pull requests merged in 2019-12, with the labels that each got.

#517 Add ctf_stats.is_pro; consolidate "pro-ness" calculations
  mods/ctf/ctf_bounties/init.lua
  mods/ctf/ctf_map/ctf_map_core/chest.lua
  mods/ctf/ctf_stats/init.lua
  mods/other/vote/vote_kick.lua
Labels: Maintenance / Code quality, Ready for review :tada:

#492 tsm_chests: Fix floating chests; remove extra bloat
  .luacheckrc
  mods/ctf/ctf_map/ctf_map_core/schem_map.lua
  mods/other/tsm_chests/init.lua
Labels: Bug / Bugfix, Maintenance / Code quality, Ready for review :tada:

#488 Add support for per-map physics modifiers
  mods/ctf/ctf_map/ctf_map_core/init.lua
  mods/ctf/ctf_map/ctf_map_core/meta_helpers.lua
  mods/ctf/ctf_map/ctf_map_core/mod.conf
  mods/ctf/ctf_map/ctf_map_core/schem_map.lua
  mods/ctf/ctf_map/map_maker/README.md
Labels: :gear: Maps, :gear: Player, :star: Feature, Ready for review :tada:

#523 Add a basic EditorConfig file
  .editorconfig
Labels: Maintenance / Code quality, Ready for review :tada:

#522 setup_maps.sh: Fix file not found
  setup_maps.sh
Labels: Maintenance / Code quality, Ready for review :tada:, Trivial

#498 ctf_map: Re-implement random map selection in a better way
  mods/ctf/ctf_map/ctf_map_core/schem_map.lua
Labels: :gear: Maps, :star: Feature, :star: Post-approval step, Ready for review :tada:

#524 [Trivial] Change the formspec message for pro side in team chest
  mods/ctf/ctf_map/ctf_map_core/chest.lua
Labels: :gear: GUI, Approved :heavy_check_mark:, Bug / Bugfix, Trivial

#526 [Trivial]Double the respective score awarded for attempt and capture
  mods/ctf/ctf_stats/init.lua
Labels: :gear: Scoring, Approved :heavy_check_mark:, Balance

#528 Change greater than operation to greater than or equal to in `is_pro`
  mods/ctf/ctf_stats/init.lua
Labels: :gear: Scoring, Approved :heavy_check_mark:, Trivial

#529 [Trivial] Change the score amount from 1k to 10k in the random message
  mods/other/random_messages/init.lua
Labels: Approved :heavy_check_mark:, Trivial

#531 ctf_bounties: Prevent the previous target from being selected again
  mods/ctf/ctf_bounties/init.lua
Labels: Approved :heavy_check_mark:, Bug / Bugfix, Trivial

#538 Tweak scoring algorithm a bit
  mods/ctf/ctf_stats/init.lua
Labels: :gear: Scoring, Approved :white_check_mark:, Balance

#545 ctf_map_core: Move treasure registration into meta_helpers.lua
  mods/ctf/ctf_map/ctf_map_core/meta_helpers.lua
  mods/ctf/ctf_map/ctf_map_core/schem_map.lua
Labels: Maintenance / Code quality, Ready for review :tada:

#547 Colourise the name of victim and killer and show bounty points.
  mods/ctf/ctf_bounties/init.lua
Labels: :gear: Chat, Approved :white_check_mark:, Feature :star:

#546 Fix colourization of messages in help page
  mods/ctf/ctf_inventory/init.lua
Labels: :gear: GUI, Approved :white_check_mark:, Bug / Bugfix, Trivial
