Repository MT-CTF/capturetheflag, pull requests merged in 2019-07, with the labels that each got.

#423 Fix aliases
  mods/ctf/ctf_map/schem_map.lua
Labels: @ Nodes, Bug / Bugfix, Trivial

#427 Update ctf_bounties to use code returned by ctf_colors.get_color()
  mods/ctf/ctf_bounties/init.lua
Labels: Bug / Bugfix, High Priority, Trivial

#421 ctf_map: Fix per-map treasures registering at server startup
  mods/ctf/ctf_map/schem_map.lua
Labels: @ Maps, Bug / Bugfix, High Priority

#426 README: Add note on update.sh
  README.md
Labels: @ Documentation, Trivial

#428 Make kill weapon detection great again!
  mods/ctf/ctf_events/init.lua
Labels: @ HUD, Bug / Bugfix, Trivial

#433 Fix flag claimed right after creation
  mods/ctf/ctf_map/schem_map.lua
Labels: @ Maps, Bug / Bugfix, High Priority, Testing needed, Trivial

#436 Trivial changes to bandages
  mods/ctf/ctf_bandages/init.lua
  mods/ctf/ctf_treasure/init.lua
Labels: Balance, Feature, Trivial

#415 Add IRC support for /maps command
  mods/ctf/ctf_map/maps_catalog.lua
Labels: @ Maps, Feature, Testing needed

#424 Fix recursive registration of ind. stairs and wool
  mods/ctf/ctf_map/nodes.lua
Labels: @ Nodes, Bug / Bugfix, Trivial

#437 Implement random spawn within team base
  mods/ctf/ctf_map/base.lua
Labels: @ AntiAbuse, Feature, Review required
