Repository MT-CTF/capturetheflag, pull requests merged in 2019-05, with the labels that each got.

#408 Change report message
  mods/other/report/init.lua
Labels: Maintenance, Trivial

#407 Fix server crash when vote kicking an already left player
  mods/other/vote/vote_kick.lua
Labels: Bug / Bugfix, High Priority

#400 Fix healing interrupted and medkit given to player on new match
  mods/pvp/medkits/init.lua
  mods/pvp/medkits/mod.conf
Labels: Bug / Bugfix, High Priority

#381 Add maps catalog
  mods/ctf/ctf_map/init.lua
  mods/ctf/ctf_map/maps_catalog.lua
  mods/ctf/ctf_map/schem_map.lua
Labels: @ Documentation, @ Maps, Feature

#412 Fix server crash caused by /maps in some edge cases
  mods/ctf/ctf_map/maps_catalog.lua
Labels: Bug / Bugfix, Trivial

#411 Add infrastructure for screenshots
  mods/ctf/ctf_map/schem_map.lua
  update.sh
Labels: @ Maps, Feature, Trivial

#414 Add random message for maps catalog
  mods/other/random_messages/init.lua
Labels: Maintenance, Trivial

#413 /maps: Add support for longer hints and licenses
  mods/ctf/ctf_map/maps_catalog.lua
  mods/ctf/ctf_map/schem_map.lua
Labels: @ Maps
