Repository MT-CTF/capturetheflag, pull requests merged in 2019-01, with the labels that each got.

#212 Reduce lava flow range from 8 to 2
  mods/default/nodes.lua
Labels: @ AntiAbuse, @ Nodes, Undecided

#312 Reduce flag drop-time from 7 minutes to 5 minutes
  minetest.conf
Labels: @ AntiAbuse, @ Gameplay Mechanics, Feature, Trivial

#329 Reorder crafting recipes to display more important recipes on first page
  mods/ctf_crafting/init.lua
Labels: @ Audiovisuals, @ Inventory, Maintenance, Trivial

#216 Provide a large set of indestructible nodes with ctf_map
  mods/ctf/ctf_map/map_maker.lua
  mods/ctf/ctf_map/nodes.lua
  mods/ctf_map/textures/ctf_map_adminpick.png
  mods/ctf_map/textures/ctf_map_ind_overlay.png
Labels: @ Maps, @ Nodes, High Priority, Testing needed

#332 Fix textures placed in the incorrect directory
  mods/ctf/ctf_map/textures/ctf_map_adminpick.png
  mods/ctf/ctf_map/textures/ctf_map_ind_overlay.png
Labels: Bugfix, High Priority, Trivial

#337 Add 'Indestructible' prefix to indestructible nodes
  mods/ctf/ctf_map/nodes.lua
Labels: @ Documentation, Maintenance
