Repository MT-CTF/capturetheflag, pull requests merged in 2020-04, with the labels that each got.

#542 Add /s chat-command alias for /summary
  mods/ctf/ctf_stats/chat.lua
Labels: :gear: Chat, Approved :white_check_mark:, Feature :star:, Trivial

#581 Rename on_skip_map to on_skip_match
  mods/ctf/ctf_match/vote.lua
  mods/ctf/ctf_stats/init.lua
Labels: :gear: Matches, Maintenance / Code quality, Ready for review :tada:

#552 Supplement Map maker's README.md
  mods/ctf/ctf_map/map_maker/README.md
Labels: :gear: Documentation, :gear: MapEditor, Ready for review :tada:

#539 Improve match duration metric; move to ctf_match
  mods/ctf/ctf_match/init.lua
  mods/ctf/ctf_match/matches.lua
  mods/ctf/ctf_stats/chat.lua
  mods/ctf/ctf_stats/gui.lua
  mods/ctf/ctf_stats/init.lua
Labels: :gear: Matches, Bug / Bugfix, Ready for review :tada:

#453 Add sniper_rifles mod
  mods/ctf/ctf_classes/classes.lua
  mods/ctf/ctf_crafting/init.lua
  mods/ctf/ctf_treasure/init.lua
  mods/other/random_messages/init.lua
  mods/pvp/sniper_rifles/LICENSE
  mods/pvp/sniper_rifles/README.md
  mods/pvp/sniper_rifles/init.lua
  mods/pvp/sniper_rifles/mod.conf
  mods/pvp/sniper_rifles/rifles.lua
  mods/pvp/sniper_rifles/sounds/sniper_rifles_rifle.ogg
  mods/pvp/sniper_rifles/textures/sniper_rifles_rifle_762.png
  mods/pvp/sniper_rifles/textures/sniper_rifles_rifle_magnum.png
Labels: :gear: Weapons, Approved :white_check_mark:, Feature :star:

#584 medkits: Remove hardcoded regen_max; use hp_max instead
  mods/pvp/medkits/init.lua
Labels: :gear: Player, Approved :white_check_mark:, Bug / Bugfix

#590 Add build status badge on README.md
  README.md
Labels: Approved :white_check_mark:, Trivial

#588 ctf_classes: Temporarily disable rocketeer class
  mods/ctf/ctf_classes/classes.lua
Labels: :gear: Classes, Approved :white_check_mark:, High Priority :grey_exclamation:

#593 Add recipe for steel and bronze block
  mods/ctf/ctf_crafting/init.lua
Labels: :gear: Inventory, :gear: Tools / Weapons, Ready for review :tada:, Trivial

#594 Increase the speed of medic by 10%
  mods/ctf/ctf_classes/classes.lua
Labels: :gear: Classes, :gear: Player, Feature :star:, Ready for review :tada:
