Repository MT-CTF/capturetheflag, pull requests merged in 2020-01, with the labels that each got.

#551 Allow wooden doors in maps
  mods/mtg/doors/init.lua
Labels: :gear: Nodes, Approved :white_check_mark:, Bug / Bugfix

#554 Disallow transfer of rankings if source and destination are same
  mods/ctf/ctf_stats/chat.lua
Labels: Approved :white_check_mark:, Bug / Bugfix, Trivial

#530 tsm_chests: Prevent chests being placed on top of other chests
  mods/other/tsm_chests/init.lua
Labels: Feature :star:, NO SQUASH :x:, Ready for review :tada:

#533 map_maker: Refactor GUI into separate file
  mods/ctf/ctf_map/map_maker/gui.lua
  mods/ctf/ctf_map/map_maker/init.lua
  mods/ctf/ctf_map/map_maker/map_maker.lua
Labels: :gear: MapEditor, Maintenance / Code quality, Ready for review :tada:
