Repository MT-CTF/capturetheflag, pull requests merged in 2020-09, with the labels that each got.

#675 Add automatic skip votes
  mods/ctf/ctf_match/vote.lua
  mods/ctf/ctf_stats/init.lua
Labels: :gear: AntiAbuse, :gear: Matches, Feature :star:, Ready for review :tada:

#656 [no squash] HUD score improvements
  mods/other/hud_score/README.md
  mods/other/hud_score/init.lua
  mods/other/hud_score/mod.conf
Labels: :gear: HUD, Bug / Bugfix, Maintenance / Code quality, NO SQUASH :x:, Ready for review :tada:

#678 Make fall damage leave at least 1 hp
  mods/pvp/anticoward/init.lua
  mods/pvp/anticoward/mod.conf
Labels: :gear: AntiAbuse, :gear: Player, Ready for review :tada:

#665 Tweak player speed [Attempt 2]
  minetest.conf
Labels: :gear: Player, Balance, Ready for review :tada:

#679 Award kill to attacker if player leaves/suicides
  mods/ctf/ctf_events/init.lua
  mods/pvp/anticoward/init.lua
Labels: :gear: AntiAbuse, :gear: Player, :gear: Scoring, Extensive testing needed :computer:, Feature :star:, High Priority :grey_exclamation:, Ready for review :tada:

#639 MTG: Trim out the remaining bloat from default
  mods/ctf/ctf_map/ctf_map_core/chest.lua
  mods/mtg/default/functions.lua
  mods/mtg/default/init.lua
  mods/mtg/default/legacy.lua
  mods/mtg/default/mapgen.lua
  mods/mtg/furnace/init.lua
  mods/other/tsm_chests/init.lua
Labels: Low Priority :sleeping:, Maintenance / Code quality, Ready for review :tada:

#650 physics: Add sanity checks and minor optimizations
  mods/other/physics/init.lua
Labels: Maintenance / Code quality, Ready for review :tada:

#661 sniper_rifles: Prioritize on un-scoping when right-clicking
  mods/pvp/sniper_rifles/init.lua
Labels: :gear: Tools / Weapons, Feature :star:, WIP :building_construction:
