Repository MT-CTF/capturetheflag, pull requests merged in 2020-05, with the labels that each got.

#601 Move flag-bearer slowdown to a separate speed modifier
  mods/ctf/ctf_classes/api.lua
  mods/ctf/ctf_match/matches.lua
Labels: :gear: Player, Ready for review :tada:

#605 [Trivial] Add sniper rifles to the good weapons list
  mods/ctf/ctf_stats/init.lua
Labels: :gear: Scoring, Approved :white_check_mark:, Trivial

#609 Add percentage based healing to bandages
  mods/ctf/ctf_bandages/init.lua
Labels: :gear: Player, Action / change needed :exclamation:, Balance, Trivial

#602 Fix crash when setting HUD
  mods/ctf/ctf_colors/hud.lua
  mods/ctf/ctf_flag/hud.lua
  mods/ctf/ctf_marker/init.lua
  mods/pvp/hud_score/init.lua
Labels: :gear: HUD, Bug / Bugfix, Ready for review :tada:

#357 Add grenades mod
  mods/ctf/ctf_crafting/init.lua
  mods/ctf/ctf_treasure/init.lua
  mods/pvp/grenades/api.md
  mods/pvp/grenades/grenades.lua
  mods/pvp/grenades/init.lua
  mods/pvp/grenades/license
  mods/pvp/grenades/mod.conf
  mods/pvp/grenades/readme.md
  mods/pvp/grenades/sounds/grenades_explode.ogg
  mods/pvp/grenades/sounds/grenades_glasslike_break.ogg
  mods/pvp/grenades/sounds/grenades_hiss.ogg
  mods/pvp/grenades/sounds/license.txt
  mods/pvp/grenades/textures/grenades_boom.png
  mods/pvp/grenades/textures/grenades_flashbang.png
  mods/pvp/grenades/textures/grenades_frag.png
  mods/pvp/grenades/textures/grenades_smoke.png
  mods/pvp/grenades/textures/grenades_smoke_grenade.png
  mods/pvp/grenades/textures/license
Labels: :gear: Tools / Weapons, Extensive testing needed :computer:, Feature :star:, Ready for review :tada:

#608 ctf_stats: Immediately write to mod storage at end of match
  mods/ctf/ctf_stats/init.lua
Labels: :gear: Scoring, Approved :white_check_mark:, Bug / Bugfix

#607 ctf_classes: Fix crash when player meta contains invalid class name
  mods/ctf/ctf_classes/api.lua
Labels: :gear: Classes, Bug / Bugfix, Ready for review :tada:, Trivial

#624 Reduce respawn immunity
  mods/ctf/ctf_inventory/init.lua
  mods/ctf/ctf_respawn_immunity/init.lua
  mods/other/random_messages/init.lua
Labels: :gear: AntiAbuse, :gear: Player, Approved :white_check_mark:, Balance, Trivial

#627 Give medic 50 bandages as initial stuff
  mods/ctf/ctf_classes/classes.lua
Labels: :gear: Classes, Balance, Ready for review :tada:, Trivial

#629 MTG: Disable mushrooms' HP regen effects
  mods/mtg/flowers/init.lua
Labels: :gear: Items / Nodes, Bug / Bugfix, Trivial

#615 Improve Grenades API
  mods/pvp/grenades/api.md
  mods/pvp/grenades/grenades.lua
  mods/pvp/grenades/init.lua
Labels: :gear: Tools / Weapons, Feature :star:, Ready for review :tada:

#606 Give medic points for healing
  .luacheckrc
  mods/ctf/ctf_classes/init.lua
  mods/ctf/ctf_classes/medic.lua
  mods/ctf/ctf_classes/mod.conf
Labels: :gear: Classes, :gear: Scoring, Feature :star:, Ready for review :tada:

#632 Attempt to fix grapples usable by firing before punching flag
  mods/ctf/ctf_classes/ranged.lua
Labels: :gear: AntiAbuse, :gear: Classes, Approved :white_check_mark:, Bug / Bugfix

#633 ctf_stats: API improvements
  mods/ctf/ctf_bounties/init.lua
  mods/ctf/ctf_classes/medic.lua
  mods/ctf/ctf_stats/chat.lua
  mods/ctf/ctf_stats/init.lua
Labels: High Priority :grey_exclamation:, Maintenance / Code quality, NO SQUASH :x:, Ready for review :tada:

#644 Prevent snipers from breaking blocks
  mods/pvp/sniper_rifles/rifles.lua
Labels: :gear: Tools / Weapons, Approved :white_check_mark:, Trivial

#645 Prevent putting class items in team chest through swapping
  mods/ctf/ctf_map/ctf_map_core/chest.lua
Labels: :gear: AntiAbuse, :gear: Inventory, Approved :white_check_mark:

#647 Fix treasure chest swapping
  mods/other/tsm_chests/init.lua
Labels: :gear: AntiAbuse, :gear: Inventory, Ready for review :tada:

#638 ctf_stats: Improve /makepro chat-command
  mods/ctf/ctf_stats/chat.lua
Labels: :gear: Chat, :gear: Scoring, Ready for review :tada:
