Repository MT-CTF/capturetheflag, pull requests merged in 2022-08, with the labels that each got.

#1016 Fix treasure string conversion
  mods/ctf/ctf_modebase/treasure.lua
Labels: Two approvals :tada:

#1018 Improve the map editor
  .luacheckrc
  mods/ctf/ctf_map/README.md
  mods/ctf/ctf_map/editor_functions.lua
  mods/ctf/ctf_map/init.lua
  mods/ctf/ctf_map/map_meta.lua
  mods/ctf/ctf_map/mapedit_gui.lua
  mods/ctf/ctf_map/mod.conf
  mods/ctf/ctf_map/nodes.lua
  mods/ctf/ctf_modebase/flags/nodes.lua
Labels: Two approvals :tada:

#1034 initial_stuff: Only give best of type
  mods/ctf/ctf_modebase/features.lua
  mods/ctf/ctf_modebase/player.lua
  mods/ctf/ctf_modes/ctf_mode_classes/init.lua
  mods/ctf/ctf_modes/ctf_mode_classic/init.lua
  mods/ctf/ctf_modes/ctf_mode_nade_fight/init.lua
Labels: Bug / Bugfix, :gear: Tools / Weapons, :gear: Inventory

#888 Crosshair HUD tweaks
  mods/ctf/ctf_combat/ctf_ranged/textures/ctf_ranged_rifle_crosshair.png
Labels: :gear: GUI / HUD / Audio, Two approvals :tada:

#1038 Add random message about sneak-jump
  mods/other/random_messages/init.lua
Labels: Trivial, Ready for review :tada:

#1042 Add random message about /donate
  mods/other/random_messages/init.lua
Labels: Trivial, One approval :white_check_mark:

#1045 ctf_chat: Prevent /msg from bypassing filter
  .luacheckrc
  mods/ctf/ctf_chat/init.lua
  mods/ctf/ctf_chat/mod.conf
Labels: Bug / Bugfix, :gear: AntiAbuse, Ready for review :tada:, One approval :white_check_mark:, :gear: Chat

#1048 ctf_chat: Replace the sender-side response for /msg
  mods/ctf/ctf_chat/init.lua
Labels: Action / change needed :exclamation:, :gear: Chat

#1043 Translate random messages
  mods/other/random_messages/init.lua
  mods/other/random_messages/locale/random_messages.de.tr
Labels: Ready for review :tada:, :gear: Translations
