Repository MT-CTF/capturetheflag, pull requests merged in 2023-08, with the labels that each got.

#1202 Fix non-diagonal borders water detect
  mods/ctf/ctf_map/map_functions.lua
Labels: Bug / Bugfix, Ready for review :tada:, :gear: Matches

#1198 Redo hpbars, add ranking resets and leagues
  .gitignore
  mods/ctf/ctf_modebase/features.lua
  mods/ctf/ctf_modebase/flags/nodes.lua
  mods/ctf/ctf_modebase/flags/taking.lua
  mods/ctf/ctf_modebase/immunity.lua
  mods/ctf/ctf_modebase/init.lua
  mods/ctf/ctf_modebase/match.lua
  mods/ctf/ctf_modebase/mod.conf
  mods/ctf/ctf_modes/ctf_mode_classes/classes.lua
  mods/ctf/ctf_modes/ctf_mode_classes/mod.conf
  mods/ctf/ctf_player/init.lua
  mods/ctf/ctf_player/models/character.b3d
  mods/ctf/ctf_player/models/character.blend
  mods/ctf/ctf_rankings/default.lua
  mods/ctf/ctf_rankings/init.lua
  mods/ctf/ctf_rankings/leagues.lua
  mods/ctf/ctf_rankings/mod.conf
  mods/ctf/ctf_rankings/ranking_reset.lua
  mods/ctf/ctf_rankings/redis.lua
  mods/ctf/ctf_rankings/textures/ctf_rankings_league_bronze.png
  mods/ctf/ctf_rankings/textures/ctf_rankings_league_diamond.png
  mods/ctf/ctf_rankings/textures/ctf_rankings_league_gold.png
  mods/ctf/ctf_rankings/textures/ctf_rankings_league_mese.png
  mods/ctf/ctf_rankings/textures/ctf_rankings_league_steel.png
  mods/ctf/ctf_rankings/textures/ctf_rankings_league_stone.png
  mods/ctf/ctf_rankings/textures/ctf_rankings_league_wood.png
  mods/other/hpbar/init.lua
  mods/other/hpbar/mod.conf
  mods/other/hpbar/textures/health_1.png
  mods/other/hpbar/textures/health_10.png
  mods/other/hpbar/textures/health_11.png
  mods/other/hpbar/textures/health_12.png
  mods/other/hpbar/textures/health_13.png
  mods/other/hpbar/textures/health_14.png
  mods/other/hpbar/textures/health_15.png
  mods/other/hpbar/textures/health_16.png
  mods/other/hpbar/textures/health_17.png
  mods/other/hpbar/textures/health_18.png
  mods/other/hpbar/textures/health_19.png
  mods/other/hpbar/textures/health_2.png
  mods/other/hpbar/textures/health_20.png
  mods/other/hpbar/textures/health_3.png
  mods/other/hpbar/textures/health_4.png
  mods/other/hpbar/textures/health_5.png
  mods/other/hpbar/textures/health_6.png
  mods/other/hpbar/textures/health_7.png
  mods/other/hpbar/textures/health_8.png
  mods/other/hpbar/textures/health_9.png
Labels: Feature :star:, :gear: Scoring, WIP :building_construction:, :gear: GUI / HUD / Audio

#1194 Victory score
  mods/ctf/ctf_modebase/features.lua
  mods/ctf/ctf_modebase/recent_rankings.lua
Labels: Feature :star:, :gear: Scoring, :gear: Matches, 🏗️ Ranked Reset Queue

#1180 add bonus for killing a flag carrier
  mods/ctf/ctf_modebase/features.lua
Labels: Feature :star:, :gear: Scoring, Trivial, 🏗️ Ranked Reset Queue

#1213 Add two random messages about `/league` and `/leagues` and a few edits
  mods/other/random_messages/init.lua
Labels: :gear: Chat

#1186 Adding 'all' option to `/r`
  mods/ctf/ctf_modebase/ranking_commands.lua
Labels: Feature :star:, Action / change needed :exclamation:

#1159 Add HP Markers
  mods/ctf/ctf_modebase/markers.lua
Labels: Feature :star:, Ready for review :tada:, :gear: GUI / HUD / Audio, Ready for Testing

#1144 A few additions to the README.md
  mods/ctf/ctf_map/README.md
Labels: :gear: MapEditor, Documentation

#1182 Add medic flag taking
  mods/ctf/ctf_combat/ctf_healing/bandage.lua
Labels: Bug / Bugfix, :gear: Tools / Weapons, Ready for review :tada:, :gear: Classes

#1201 Drop the nade with illegal explode points if the thrower is dead
  mods/pvp/grenades/grenades.lua
Labels: Bug / Bugfix, :gear: Tools / Weapons, :gear: PVP, Ready for review :tada:

#1219 Check for captured team in smoke nade
  mods/pvp/grenades/grenades.lua
  mods/pvp/grenades/mod.conf
Labels: Bug / Bugfix, :gear: Tools / Weapons
