Repository MT-CTF/capturetheflag, pull requests merged in 2023-07, with the labels that each got.

#1145 Add sounds when player drops flag
  mods/ctf/ctf_modebase/features.lua
  mods/ctf/ctf_modebase/sounds/ctf_modebase_drop_flag_negative.ogg
  mods/ctf/ctf_modebase/sounds/ctf_modebase_drop_flag_positive.ogg
Labels: Feature :star:, :gear: GUI / HUD / Audio

#1149 Prevent placement of markers while sniping
  mods/ctf/ctf_modebase/markers.lua
Labels: Bug / Bugfix, :gear: Tools / Weapons, :gear: Classes

#1167 Add a list containing fall damage factors
  mods/mtg/ctf_changes/init.lua
Labels: :gear: Nodes, Action / change needed :exclamation:

#1185 Change donation limits
  mods/ctf/ctf_modebase/ranking_commands.lua
Labels: :gear: Scoring, Trivial, Ready for review :tada:, :gear: Matches
