Repository MT-CTF/capturetheflag, pull requests merged in 2024-11, with the labels that each got.

#1350 allow donating maximum score by donating 0 or less
  mods/ctf/ctf_modebase/ranking_commands.lua
Labels: :gear: Scoring, Trivial, Ready for review :tada:, One approval :white_check_mark:, :gear: Chat

#1354 Correction of loot points in team chests
  mods/ctf/ctf_teams/team_chest.lua
Labels: :gear: Tools / Weapons, Trivial, One approval :white_check_mark:

#1358 fix punctuation in cooldown message
  mods/ctf/ctf_modes/ctf_mode_classes/classes.lua
Labels: Bug / Bugfix, Trivial, One approval :white_check_mark:, :gear: Chat
