Repository MT-CTF/capturetheflag, pull requests merged in 2024-05, with the labels that each got.

#1287 Tell players how much the capture was worth
  mods/ctf/ctf_modebase/features.lua
Labels: Feature :star:, :gear: GUI / HUD / Audio, :gear: Chat

#1266 Prevent class switch cooldown if switching to the same class as before
  mods/ctf/ctf_modes/ctf_mode_classes/classes.lua
Labels: Bug / Bugfix, Trivial, :gear: Classes, Two approvals :tada:

#1270 Add Spanish translations where applicable
  mods/ctf/ctf_report/locale/ctf_report.es.tr
  mods/other/afkkick/locale/afkkick.es.tr
  mods/other/random_messages/locale/random_messages.es.tr
  mods/other/random_messages/locale/template.txt
  mods/other/select_item/locale/select_item.de.tr
  mods/other/select_item/locale/select_item.es.tr
  mods/other/select_item/locale/template.txt
  mods/other/throwable_snow/locale/throwable_snow.es.tr
Labels: :gear: Translations

#1173 give score for items removed from enemies
  mods/ctf/ctf_teams/team_chest.lua
  mods/pvp/dropondie/init.lua
Labels: Feature :star:, :gear: Scoring, :gear: Inventory, Post-approval step :star:, 🏗️ Ranked Reset Queue
