Repository MT-CTF/capturetheflag, pull requests merged in 2024-07, with the labels that each got.

#1312 Fix bug - Poison grenades deal no damage to enemies.
  mods/pvp/grenades/grenades.lua
Labels: Bug / Bugfix, :gear: Tools / Weapons, One approval :white_check_mark:

#1307 Prevent item's special ability from activating during build time.
  mods/ctf/ctf_modes/ctf_mode_classes/classes.lua
Labels: Feature :star:, :gear: Matches

#1322 Update ranking_commands.lua
  mods/ctf/ctf_modebase/ranking_commands.lua
Labels: Bug / Bugfix, Trivial, One approval :white_check_mark:, :gear: Chat

#1324 Team chat modification
  mods/ctf/ctf_chat/init.lua
Labels: Feature :star:, Trivial, :gear: Chat
