Repository MT-CTF/capturetheflag, pull requests merged in 2024-12, with the labels that each got.

#1001 Introduce Landmines
  mods/ctf/ctf_landmine/init.lua
  mods/ctf/ctf_landmine/mod.conf
  mods/ctf/ctf_landmine/textures/ctf_landmine_landmine.png
  mods/ctf/ctf_modebase/crafting.lua
  mods/ctf/ctf_modebase/features.lua
  mods/ctf/ctf_modes/ctf_mode_classes/init.lua
  mods/ctf/ctf_modes/ctf_mode_nade_fight/init.lua
Labels: :gear: Tools / Weapons, Action / change needed :exclamation:, Ready for review :tada:, Ready for Testing

#1365 Few Redef Mod Fixes
  mods/mtg/redef/redefinitions/3d_ladders.lua
Labels: Bug / Bugfix, :gear: Nodes, Trivial

#1367 Change `minetest` to `core` in `crafting` mod
  mods/other/crafting/api.lua
  mods/other/crafting/gui.lua
  mods/other/crafting/init.lua
Labels: Maintenance / Performance, Trivial

#1366 New liquid: Poisonous Water
  .luacheckrc
  mods/other/poison_water/README.txt
  mods/other/poison_water/init.lua
  mods/other/poison_water/mod.conf
  mods/other/poison_water/textures/bucket_poision_water.png
Labels: Feature :star:, :gear: Nodes, :gear: MapEditor, Non-trivial
