Repository MT-CTF/capturetheflag, pull requests merged in 2024-06, with the labels that each got.

#1196 add flag attempt streaks
  mods/ctf/ctf_modebase/flags/taking.lua
  mods/ctf/ctf_modebase/init.lua
Labels: Feature :star:, Ready for Testing

#1306 Show message to healer on healing a player, and the player who died that the killer got x points
  mods/ctf/ctf_modebase/features.lua
Labels: Feature :star:, :gear: PVP, :gear: GUI / HUD / Audio

#1286 Add concept of HUD events channels and add the flag events to channel 1
  mods/apis/hud_events/init.lua
  mods/ctf/ctf_modebase/flags/huds.lua
Labels: Bug / Bugfix, Ready for review :tada:, :gear: GUI / HUD / Audio

#1265 Use voxel manip for barrier placing commands
  mods/ctf/ctf_map/init.lua
Labels: Bug / Bugfix, :gear: Maps, :gear: Nodes, Ready for review :tada:

#1303 Change donate command to accept multiple recipients
  mods/ctf/ctf_modebase/ranking_commands.lua
Labels: Feature :star:, :gear: Scoring

#1320 Show classes about info even during cooldown period.
  mods/ctf/ctf_modes/ctf_mode_classes/classes.lua
Labels: Feature :star:, Action / change needed :exclamation:, :gear: Classes
