Repository MT-CTF/capturetheflag, pull requests merged in 2025-05, with the labels that each got.

#1369 New Documentation
  CONTRIBUTING.md
  README.md
  docs/ctf-api.md
Labels: Action / change needed :exclamation:, Documentation

#1047 Add the hudbars mod
  .luacheckrc
  mods/apis/ctf_settings/global_settings.lua
  mods/other/hpbar_hud/init.lua
  mods/other/minetest_hudbars/.mailmap
  mods/other/minetest_hudbars/API.md
  mods/other/minetest_hudbars/README.md
  mods/other/minetest_hudbars/default_settings.lua
  mods/other/minetest_hudbars/init.lua
  mods/other/minetest_hudbars/locale/hudbars.de.tr
  mods/other/minetest_hudbars/locale/hudbars.es.tr
  mods/other/minetest_hudbars/locale/hudbars.it.tr
  mods/other/minetest_hudbars/locale/hudbars.ms.tr
  mods/other/minetest_hudbars/locale/hudbars.nl.tr
  mods/other/minetest_hudbars/locale/hudbars.pt.tr
  mods/other/minetest_hudbars/locale/hudbars.ru.tr
  mods/other/minetest_hudbars/locale/hudbars.tr.tr
  mods/other/minetest_hudbars/locale/template.txt
  mods/other/minetest_hudbars/mod.conf
  mods/other/minetest_hudbars/screenshot.png
  mods/other/minetest_hudbars/settingtypes.txt
  mods/other/minetest_hudbars/textures/hudbars_bar_background.png
  mods/other/minetest_hudbars/textures/hudbars_bar_breath.png
  mods/other/minetest_hudbars/textures/hudbars_bar_health.png
  mods/other/minetest_hudbars/textures/hudbars_bgicon_breath.png
  mods/other/minetest_hudbars/textures/hudbars_bgicon_health.png
  mods/other/minetest_hudbars/textures/hudbars_icon_breath.png
  mods/other/minetest_hudbars/textures/hudbars_icon_health.png
  mods/other/sprint/init.lua
  mods/other/sprint/textures/sprint_stamina_bar.png
Labels: Ready for review :tada:, :gear: GUI / HUD / Audio

#1179 Add Death Message
  mods/ctf/ctf_modebase/features.lua
Labels: Feature :star:, Action / change needed :exclamation:, :gear: PVP
